/* Main Vue File: Configuration & Init */

import Vue from 'vue'
import App from './App.vue'
import VueRouter from 'vue-router'

// Import CSS component framework
import VueMaterial from 'vue-material'
import 'vue-material/dist/vue-material.min.css'
import 'vue-material/dist/theme/default.css'


// Tell Vue which packages to use
Vue.use(VueRouter)
Vue.use(VueMaterial)

// Autogenerated by vue-cli
Vue.config.productionTip = false

// Vue Routing: Connect URLs with Components
import ProjectIdeaOverview from './pages/ProjectIdeaOverview.vue';
import ProjectOverview from './pages/ProjectOverview.vue';
import AddProject from './pages/AddProject.vue';
import EditProject from './pages/EditProject.vue';

const routes = [{
    path: '/',
    component: ProjectIdeaOverview
  },
  {
    path: '/add',
    component: AddProject
  },
  {
    path: '/edit/:id',
    component: EditProject
  },
  {
    path: '/projects',
    component: ProjectOverview
  }
];

// Init new VueRouter with described routes
const router = new VueRouter({
  routes
})


// Init new Vue Instance with previously created crouter and App.
// The HTML element that Vue renders everything in, is defined by an HTML id (in this case: "#app")
new Vue({
  router,
  render: h => h(App),
}).$mount('#app')